- name: including variables.
  include_vars:
    dir: vars
- name: getting info of webservers[running/stopped] from AWS.
  ec2_instance_info:
    region: "{{ region }}"
    filters:
      "tag:app": ["web"]
      instance-state-name: ["running","stopped"]
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
  register: gathered_data
- name: updating variable file with webservers info.
  template:
    src: "templates/gather_data.j2"
    dest: "{{ role_path }}/vars/main.yml"
  changed_when: False
- name: refreshing variables
  include_vars:
    dir: vars
    files_matching: main.yml
- name: starting existing webservers if already present in AWS.
  block:
    - ec2_instance:
        state: running
        region: "{{ region }}"
        instance_ids: "{{ item.instance_id }}"
        instance_type: "{{ instance_type }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
      loop: "{{ instance_data }}"
  rescue:
    - debug:
        var: instance_data
- debug: 
    msg: "you have {{ web_count }} webservers."
- pause:
    prompt: "enter how many more webservers you want to launch, enter 0 for none."
    echo: yes
  register: result_web
- name: launching more webservers, if required.
  ec2_instance:
    name: "{{ name }}"
    count: "{{ result_web.user_input }}"
    region: "{{ region }}"
    image_id: "{{ image_id }}"
    instance_type: "{{ instance_type }}"
    key_name: "{{ key_name }}"
    tags:
      app: "web"
    network:
      assign_public_ip: true
    security_group: "{{ security_group }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    state: running
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
  when: (result_web.user_input | int) > 0
- name: refreshing inventory.
  meta: refresh_inventory
